services:
  ai-planner:
    image: theanh2906/ai-planner
    container_name: ai-planner
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3010:3010'
    environment:
      - NODE_ENV=production
      - PORT=3010
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - VISUAL_CROSSING_API_KEY=${VISUAL_CROSSING_API_KEY}
    restart: always
